packages:
  - '.'
  - 'examples/*'
allowBuilds:
  esbuild: true
  protobufjs: set this to true or false
minimumReleaseAgeExclude:
  - '@ai-sdk/deepseek@3.0.36'
  - '@ai-sdk/gateway@4.0.68'
  - '@ai-sdk/provider-utils@5.0.33'
  - ai@7.0.84
